name: Update Image Tag

permissions:
  contents: write

on:
  workflow_run:
    workflows: ["Build and Publish Image"]
    types:
      - completed

jobs:
  update-image-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update image versions in YAML files
      run: |
        find . -type f -name '*.yaml' -print0 | while IFS= read -r -d $'\0' file; do
          if grep -q -E 'image:[[:space:]]+[^:]+:[^ ]+' "$file"; then
            sed -i -E "s|(image:[[:space:]]+[^:]+):[^ ]+|\1:${NEW_IMAGE_TAG}|" "$file"
            git add "$file"
          fi
        done

    - name: Update image tag in Markdown files
      run: |
        find . -type f -name '*.md' -print0 | while IFS= read -r -d $'\0' file; do
          if grep -q -E 'jeanfrg\/app1:[^ ]+' "$file"; then
            sed -i -E "s|(jeanfrg/app1):[^ ]+|\1:${NEW_IMAGE_TAG}|" "$file"
            git add "$file"
          fi
        done

    - name: Commit and push changes
      env: 
        CI_COMMIT_MESSAGE: Updated image tag to ${NEW_IMAGE_TAG}
        CI_COMMIT_AUTHOR: GitHub Action
      run: |
        git config --global user.email "action@github.com"
        git config --global  user.name "GitHub Action"
        git commit -m "Updated image tag to ${NEW_IMAGE_TAG}"
        git push
